# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\tscheduler\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"W\n\x10SchedulerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x15target_service_method\x18\x02 \x01(\t\x12\x16\n\x0erepeat_minutes\x18\x03 \x01(\x05\"d\n\x11SchedulerResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1d\n\x15target_service_method\x18\x03 \x01(\t\x12\x16\n\x0erepeat_minutes\x18\x04 \x01(\x05\"i\n\x16ModifySchedulerRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1d\n\x15target_service_method\x18\x03 \x01(\t\x12\x16\n\x0erepeat_minutes\x18\x04 \x01(\x05\"A\n\rSchedulerList\x12\x30\n\nschedulers\x18\x01 \x03(\x0b\x32\x1c.scheduler.SchedulerResponse2\xfa\x01\n\x10SchedulerService\x12L\n\x0f\x43reateScheduler\x12\x1b.scheduler.SchedulerRequest\x1a\x1c.scheduler.SchedulerResponse\x12\x44\n\x10GetAllSchedulers\x12\x16.google.protobuf.Empty\x1a\x18.scheduler.SchedulerList\x12R\n\x0fModifyScheduler\x12!.scheduler.ModifySchedulerRequest\x1a\x1c.scheduler.SchedulerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCHEDULERREQUEST']._serialized_start=92
  _globals['_SCHEDULERREQUEST']._serialized_end=179
  _globals['_SCHEDULERRESPONSE']._serialized_start=181
  _globals['_SCHEDULERRESPONSE']._serialized_end=281
  _globals['_MODIFYSCHEDULERREQUEST']._serialized_start=283
  _globals['_MODIFYSCHEDULERREQUEST']._serialized_end=388
  _globals['_SCHEDULERLIST']._serialized_start=390
  _globals['_SCHEDULERLIST']._serialized_end=455
  _globals['_SCHEDULERSERVICE']._serialized_start=458
  _globals['_SCHEDULERSERVICE']._serialized_end=708
# @@protoc_insertion_point(module_scope)
